### ISSUE TITLE
[BUG] testMultiLineDirections test does not follow the spec

### ISSUE THREAD

**Issue by paul-louyot** [cooklang/cooklang-ts#30]
**Describe the bug**

The spec states that separate steps should be separated with an empty line: "Each paragraph in your recipe file is a cooking step. Separate steps with an empty line.", but the test called `testMultiLineDirections` shows that two directions separated by a single line return are interpreted as two different steps.

**To Reproduce**

Check content of `testMultiLineDirections` in `tests/canonical.yaml`, which is about parsing the string "Add a bit of chilli\nAdd a bit of hummus"

**Current behavior**

The `result` section of the test reads:
```
      steps:
        -
          - type: text
            value: "Add a bit of chilli"
        -
          - type: text
            value: "Add a bit of hummus"
      metadata: []
```

**Expected behavior**

The result of the test should be
```
    result:
      steps:
        -
          - type: text
            value: "Add a bit of chilli\nAdd a bit of hummus"
      metadata: []
```
